var swpRightHTML  ='<div class="swpRightPos">';
swpRightHTML  +=	'<a href="#" class="swpRightPosButton">';
swpRightHTML  +=		'<span class="icon-cog"></span>';
swpRightHTML  +=	'</a>';
swpRightHTML  +=	'<div class="sc_tabs">';
swpRightHTML  +=		'<ul class="tabsMenuHead" role="tablist">';
swpRightHTML  +=			'<li class="right_tab_custom" role="tab" aria-controls="tabsCustom" aria-labelledby="tabsCustom_1">';
swpRightHTML  +=				'<a class="tabsCustom" href="#tabsCustom" title="Custom panel" role="presentation" id="tabsCustom_1"></a>';
swpRightHTML  +=			'</li>';
swpRightHTML  +=			'<li class="right_tab_favorites" role="tab" aria-controls="tabsFavorite" aria-labelledby="tabsFavorite_1">';
swpRightHTML  +=				'<a class="tabsFavorite" href="#tabsFavorite" title="Bookmarks" role="presentation" id="tabsFavorite_1"></a>';
swpRightHTML  +=			'</li>';
swpRightHTML  +=		'</ul>';
swpRightHTML  +=		'<div id="tabsCustom" class="tabsMenuBody" aria-labelledby="tabsCustom_1" role="tabpanel">';
swpRightHTML  +=			'<div id="custom_options">';
swpRightHTML  +=				'<div id="custom_options_scroll" class="sc_scroll sc_scroll_vertical swiper-slider-container scroll-container custom_options_scroll swiper-free-mode">';
swpRightHTML  +=					'<div class="sc_scroll_wrapper swiper-wrapper">';
swpRightHTML  +=						'<div class="sc_scroll_slide swiper-slide">';
swpRightHTML  +=							'<div class="co_header">';
swpRightHTML  +=								'<h4 class="co_title">Choose Your Style</h4>';
swpRightHTML  +=								'<a href="#" class="co_reset_to_default icon-arrows-ccw" title="Reset to default"></a>';
swpRightHTML  +=							'</div>';
swpRightHTML  +=							'<div class="co_options">';
swpRightHTML  +=								'<form name="co_form">';
swpRightHTML  +=									'<input type="hidden" id="co_site_url" name="co_site_url" value="index.html">';
swpRightHTML  +=									'<div class="co_form_row">';
swpRightHTML  +=										'<input type="hidden" name="co_body_style" value="fullscreen">';
swpRightHTML  +=										'<span class="co_label">Body style:</span>';
swpRightHTML  +=										'<div class="co_switch_box">';
swpRightHTML  +=											'<a href="#" class="co_switch_label wide">Wide</a>';
swpRightHTML  +=											'<div class="switcher">';
swpRightHTML  +=												'<a href="#" class="ui-draggable ui-draggable-handle"></a>';
swpRightHTML  +=											'</div>';
swpRightHTML  +=											'<a href="#" class="co_switch_label boxed">Boxed</a>';
swpRightHTML  +=										'</div>';
swpRightHTML  +=									'</div>';
swpRightHTML  +=									'<div class="co_form_row">';
swpRightHTML  +=										'<span class="co_label">Theme colors:</span>';
swpRightHTML  +=										'<div class="co_form_subrow">';
swpRightHTML  +=											'<input type="hidden" name="co_theme_color" value="#fa6839">';
swpRightHTML  +=											'<div id="co_theme_color" class="iColorPicker"></div>';
swpRightHTML  +=											'<input type="hidden" name="co_theme_color_1" value="#1f9ad6">';
swpRightHTML  +=											'<div id="co_theme_color_1" class="iColorPicker"></div>';
swpRightHTML  +=											'<input type="hidden" name="co_theme_color_2" value="#98bd15">';
swpRightHTML  +=											'<div id="co_theme_color_2" class="iColorPicker"></div>';
swpRightHTML  +=										'</div>';
swpRightHTML  +=									'</div>';
swpRightHTML  +=									'<div class="co_form_row">';
swpRightHTML  +=										'<input type="hidden" name="co_bg_pattern" value="">';
swpRightHTML  +=										'<span class="co_label">Theme pattern:</span>';
swpRightHTML  +=										'<div id="co_bg_pattern_list">';
swpRightHTML  +=											'<a href="#" id="pattern_1" class="co_pattern_wrapper">';
swpRightHTML  +=												'<img src="custom_menu/img/pattern_1_thumb2.png" alt="">';
swpRightHTML  +=											'</a>';
swpRightHTML  +=											'<a href="#" id="pattern_2" class="co_pattern_wrapper">';
swpRightHTML  +=												'<img src="custom_menu/img/pattern_2_thumb2.png" alt="">';
swpRightHTML  +=											'</a>';
swpRightHTML  +=											'<a href="#" id="pattern_3" class="no_margin co_pattern_wrapper">';
swpRightHTML  +=												'<img src="custom_menu/img/pattern_3_thumb2.png" alt="">';
swpRightHTML  +=											'</a>';
swpRightHTML  +=										'</div>';
swpRightHTML  +=									'</div>';
swpRightHTML  +=									'<div class="co_form_row">';
swpRightHTML  +=										'<input type="hidden" name="co_bg_image" value="">';
swpRightHTML  +=										'<span class="co_label">Backgroud images:</span>';
swpRightHTML  +=										'<div id="co_bg_images_list">';
swpRightHTML  +=											'<a href="#" id="image_1" class="co_image_wrapper">';
swpRightHTML  +=												'<img src="custom_menu/img/image_1_thumb2.jpg" alt="">';
swpRightHTML  +=											'</a>';
swpRightHTML  +=											'<a href="#" id="image_2" class="co_image_wrapper">';
swpRightHTML  +=												'<img src="custom_menu/img/image_2_thumb2.jpg" alt="">';
swpRightHTML  +=											'</a>';
swpRightHTML  +=											'<a href="#" id="image_3" class="no_margin co_image_wrapper">';
swpRightHTML  +=												'<img src="custom_menu/img/image_3_thumb2.jpg" alt="">';
swpRightHTML  +=											'</a>';
swpRightHTML  +=										'</div>';
swpRightHTML  +=										'<div id="co_bg_images"></div>';
swpRightHTML  +=									'</div>';
swpRightHTML  +=								'</form>';
swpRightHTML  +=							'</div>';
swpRightHTML  +=						'</div>';
swpRightHTML  +=					'</div>';
swpRightHTML  +=					'<div id="custom_options_scroll_bar" class="sc_scroll_bar sc_scroll_bar_vertical custom_options_scroll_bar">';
swpRightHTML  +=						'<div class="swiper-scrollbar-drag swiper-scrollbar-cursor-drag"></div>';
swpRightHTML  +=					'</div>';
swpRightHTML  +=				'</div>';
swpRightHTML  +=			'</div>';
swpRightHTML  +=		'</div>';
swpRightHTML  +=		'<div id="tabsFavorite" class="tabsMenuBody" aria-labelledby="tabsFavorite_1" role="tabpanel">';
swpRightHTML  +=			'<div class="addBookmarkArea">';
swpRightHTML  +=				'<a href="#" class="addBookmark">add bookmark</a>';
swpRightHTML  +=			'</div>';
swpRightHTML  +=			'<div class="sc_scroll sc_scroll_vertical swiper-slider-container scroll-container scroll-no-swiping" id="bookmarks_scroll">';
swpRightHTML  +=				'<div class="sc_scroll_wrapper swiper-wrapper">';
swpRightHTML  +=					'<div class="sc_scroll_slide swiper-slide swiper-no-swiping">';
swpRightHTML  +=						'<ol class="listBookmarks"></ol>';
swpRightHTML  +=					'</div>';
swpRightHTML  +=				'</div>';
swpRightHTML  +=				'<div id="bookmarks_scroll_bar" class="sc_scroll_bar sc_scroll_bar_vertical bookmarks_scroll_bar"></div>';
swpRightHTML  +=			'</div>';
swpRightHTML  +=		'</div>';
swpRightHTML  +=	'</div>';
swpRightHTML  +='</div>';

jQuery('body').append(swpRightHTML);